#!/usr/bin/env python3
"""How much of production's decode time actually runs beside a fresh prefill -- the ceiling on every anti-interference lever.

R585 established the mechanism: a generation loses throughput when a large prompt arrives beside it and
interleaves its chunked prefill with the decode steps (0.65x under ~45k arrivals, 0.86x under ~750-token ones).
Four rounds were then spent asking whether chunk_size is a lever on it, and none of them answered, because the
interferer is generated by the scheduler under test -- equalise arrival count and dwell diverges, equalise dwell
and count diverges.

THIS ASKS THE QUESTION THAT PRICES ALL OF THEM, AND IT COSTS NO GPU. Whatever a lever recovers, it can only
recover it during decode that is actually exposed to a resident prefill. Measure that fraction on real traffic
and you have an upper bound on the entire programme -- chunk_size, decode-priority scheduling, admission
shaping. If exposure is a few per cent, the lever hunt is closed by arithmetic. If it is a third, the next GPU
hour is justified.

It needs no modelling, because the server already logs both halves per request:

    #257 chat/completions: 126 tokens generated at 68.1 T/s · prompt 42,248 tokens, 99% cached,
         520 new in 0.22 s (2,364 T/s) · first token 0.24 s, total 2.09 s · draft 67/82 accepted (82%)

  "520 new in 0.22 s"  -> the MEASURED uncached work and the MEASURED wall it was resident for, contention
                          included. No prefill-rate assumption is needed, which matters: the only available
                          estimate (49k in 12.2 s) came from a saturated harness.
  "first token 0.24 s, total 2.09 s" + the line's own timestamp -> the request's decode interval.

So each request contributes a prefill interval [start, start+P] and a decode interval [start+TTFT, end], and
exposure is the share of decode-stream-seconds overlapping some OTHER request's prefill interval.

  prefill_exposure.py <container log> [--min-new 4000]

--min-new sets what counts as a "substantial" prefill: R585 measured 0.65x under ~45k arrivals and 0.86x under
~750-token ones, so exposure to a 300-token prefill is not the same event and is reported separately.
"""
import argparse, re, statistics as st, sys

# The completion line is wrapped across continuation lines by the server's formatter, so the file is joined on
# the timestamp boundary before matching. Fields are optional in the regex on purpose: a request that produced
# no draft block, or hit an error, should be skipped rather than crash the pass.
TS = re.compile(r"^(\d\d):(\d\d):(\d\d)\.(\d+)\s")
# THE CACHED FIELD HAS TWO SPELLINGS AND THE SECOND ONE IS THE IMPORTANT ONE. A request that hit no prefix at
# all prints "none cached", not "0% cached". Matching only the percent form silently dropped 221 of 9,926
# requests here -- and they are not a random 221: they are precisely the fully-uncached ones, the fresh prefills
# this whole measurement exists to count. Dropping them biases the exposure DOWN, which for a bound used to
# close lines of work is the dangerous direction. Found 2026-09-20 by checking the reject list instead of
# trusting a 98 % parse rate.
DONE = re.compile(
    r"#(\d+)\s+\S+:\s+([\d,]+)\s+tokens generated at\s+([\d.]+)\s+T/s.*?"
    r"prompt\s+([\d,]+)\s+tokens,\s+(?:(\d+)%|(none))\s+cached,\s+([\d,]+)\s+new in\s+([\d.]+)\s*s.*?"
    r"first token\s+([\d.]+)\s*s,\s+total\s+([\d.]+)\s*s", re.S)


def num(s):
    return float(s.replace(",", ""))


def parse(path):
    """-> [(end_epoch_s, gen_tokens, prompt, cached_pct, new_tokens, prefill_s, ttft_s, total_s)]"""
    recs = []
    cur, cur_ts = [], None
    prev_h = None
    day = 0
    with open(path, errors="replace") as fh:
        for line in fh:
            m = TS.match(line)
            if m:
                if cur_ts is not None and cur:
                    recs.append((cur_ts, " ".join(cur)))
                h, mi, s, frac = int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4)
                # the log carries no date, so a wrap past midnight has to be inferred from the hour going back
                if prev_h is not None and h < prev_h - 12:
                    day += 1
                prev_h = h
                cur_ts = day * 86400 + h * 3600 + mi * 60 + s + float("0." + frac)
                cur = [line[m.end():].strip()]
            elif cur_ts is not None:
                cur.append(line.strip())
    if cur_ts is not None and cur:
        recs.append((cur_ts, " ".join(cur)))

    out = []
    for ts, body in recs:
        m = DONE.search(body)
        if not m:
            continue
        cached = 0.0 if m.group(6) else float(m.group(5))   # "none cached" -> 0 %
        out.append((ts, num(m.group(2)), num(m.group(4)), cached, num(m.group(7)),
                    float(m.group(8)), float(m.group(9)), float(m.group(10))))
    return out


def union_len(iv):
    """Total length of a union of intervals, and the merged list."""
    if not iv:
        return 0.0, []
    iv = sorted(iv)
    merged = [list(iv[0])]
    for a, b in iv[1:]:
        if a <= merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], b)
        else:
            merged.append([a, b])
    return sum(b - a for a, b in merged), merged


def overlap(a0, a1, merged):
    """Length of [a0,a1) covered by a merged (disjoint, sorted) interval list."""
    tot = 0.0
    for b0, b1 in merged:
        if b1 <= a0:
            continue
        if b0 >= a1:
            break
        tot += min(a1, b1) - max(a0, b0)
    return tot


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("log")
    ap.add_argument("--min-new", type=float, default=4000,
                    help="uncached tokens above which a prefill counts as substantial (R585's damaging kind)")
    a = ap.parse_args()

    r = parse(a.log)
    if not r:
        print("no completion lines parsed -- is this a TabbyAPI container log?")
        return 1

    span = max(x[0] for x in r) - min(x[0] - x[7] for x in r)
    gen = sum(x[1] for x in r)
    print(f"{len(r):,} requests over {span/3600:.2f} h, {gen:,.0f} generated tokens\n")

    newt = sorted(x[4] for x in r)
    cached = sorted(x[3] for x in r)
    print("what the uncached work actually looks like (this is the resource a chunk/scheduling lever governs):")
    print(f"  uncached tokens/request : median {st.median(newt):>8,.0f}  p90 {newt[int(.9*len(newt))]:>8,.0f}  "
          f"p99 {newt[int(.99*len(newt))]:>8,.0f}  max {newt[-1]:>9,.0f}")
    print(f"  cached share            : median {st.median(cached):>8.0f}%  p10 {cached[int(.1*len(cached))]:>7.0f}%")
    sub = [x for x in r if x[4] >= a.min_new]
    print(f"  requests with >= {a.min_new:,.0f} uncached tokens : {len(sub):,} "
          f"({len(sub)/len(r)*100:.1f}% of requests, {sum(x[4] for x in sub)/sum(x[4] for x in r)*100:.0f}% of "
          f"all uncached tokens)")
    print(f"  total uncached prefill seconds : {sum(x[5] for x in r):,.0f} s of a {span:,.0f} s window "
          f"({sum(x[5] for x in r)/span*100:.1f}% duty, summed over concurrent requests)\n")

    # Each request occupies a prefill interval and then a decode interval. The prefill wall is MEASURED, so it
    # already carries whatever contention it suffered; no service-rate model is involved anywhere here.
    pre_all, pre_sub, dec = [], [], []
    for ts, g, p, c, nt, ps, tt, tot in r:
        s0 = ts - tot
        pre_all.append((s0, s0 + ps))
        if nt >= a.min_new:
            pre_sub.append((s0, s0 + ps))
        d0 = s0 + tt
        if ts > d0:
            dec.append((d0, ts, g))

    _, m_all = union_len([x for x in pre_all])
    _, m_sub = union_len([x for x in pre_sub])
    dec_secs = sum(b - a_ for a_, b, _ in dec)
    print("EXPOSURE -- the share of decode that runs beside a resident prefill.")
    print("This is the ceiling on every anti-interference lever: work that is never exposed cannot be recovered.\n")
    for label, merged in (("any prefill", m_all), (f">= {a.min_new:,.0f} uncached", m_sub)):
        ov = sum(overlap(d0, d1, merged) for d0, d1, _ in dec)
        # token-weighted: decode seconds are not equally valuable, tokens are what is lost
        ovt = sum(g * (overlap(d0, d1, merged) / (d1 - d0)) for d0, d1, g in dec if d1 > d0)
        print(f"  exposed to {label:<22} {ov/dec_secs*100:5.1f}% of decode-stream-seconds, "
              f"{ovt/gen*100:5.1f}% of generated tokens")

    # THE BOUND MUST BE SIZE-MATCHED, and this is the trap the whole four-round saga fell into. R585 measured
    # TWO losses, against two arrival sizes: 0.65x under ~45k prefills and 0.86x under ~750-token ones. Every
    # chunk harness reproduced the 45k case because that is where the effect is large -- and the exposure figures
    # above say production almost never sees it. Pairing production's exposure with the 45k loss would be
    # measuring one regime and pricing another.
    ov_all = sum(overlap(d0, d1, m_all) for d0, d1, _ in dec) / dec_secs
    ov_sub = sum(overlap(d0, d1, m_sub) for d0, d1, _ in dec) / dec_secs
    med_new = st.median(newt)
    loss = 0.35 if med_new >= a.min_new else 0.14   # R585: 0.65x at ~45k, 0.86x at ~750 tokens
    print(f"\n  UPPER BOUND on what any anti-interference lever can recover on THIS traffic:")
    print(f"    the exposure is dominated by ordinary prefills (median {med_new:,.0f} uncached tokens), and")
    print(f"    R585's measured loss at that arrival size is 0.86x, not the 0.65x it measured at ~45k.")
    print(f"      {ov_all*100:.1f}% exposed  x  {loss*100:.0f}% loss  =  {ov_all*loss*100:.1f}% of decode")
    print(f"    The damaging ~45k regime every chunk harness reproduced covers {ov_sub*100:.1f}% of decode here,")
    print(f"    so pricing it against R585's 0.65x gives {ov_sub*0.35*100:.2f}%.")
    print(f"    Both assume a lever recovers ALL of the loss on ALL exposed decode, which none will.")
    print(f"\n  Window aggregate {gen/span:.0f} t/s counts idle wall; the decode-busy figure comparable to")
    print(f"  R586's 306.3 t/s is in tabby_log_agg.py, not here.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
